# permissions for end users to edit onionbalancedservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onionbalancedservice-editor-role
rules:
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionbalancedservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionbalancedservices/status
  verbs:
  - get
