
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionbalancedservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionbalancedservices/finalizers
  verbs:
  - update
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionbalancedservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionservices/finalizers
  verbs:
  - update
- apiGroups:
  - tor.k8s.torproject.org
  resources:
  - onionservices/status
  verbs:
  - get
  - patch
  - update
